### ISSUE TITLE
Windows display scaling affects movement precision in function block network editors

### ISSUE THREAD

**Issue by rudoc** [eclipse-4diac/4diac-ide#1978]
When using the IDE on monitors with Windows display scaling enabled, attempting to move graphical elements (such as function blocks or connections) in the network editor results in excessive and unexpected displacement. The elements do not follow the cursor precisely, making fine-grained layout adjustments difficult or impossible.

![Image](https://github.com/user-attachments/assets/e915e3ab-72af-428c-8587-17836ba2cd35)

```
4diac IDE 
Version: 3.0.100
Build id: 2025-12-20_0703
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 25.0.1+8-LTS
Java version: 25.0.1
```

**Comment by azoitl** [comment]
@rudoc I currently have no easy access to a windows machine for testing could add the following line at the and of your `4diac-ide.ini` file

`-Ddraw2d.enableAutoscale=false`

This should theoretically solve the issue but may lead to less nice drawings.

**Comment by rudoc** [comment]
@azoitl 
Yes, adding this option to the .ini file resolved the movement issues for function blocks and connections. It also corrected the scaling problem in the Palette tab. With this fix, my user experience is now good again!
The drawings are fine by me. There's no difference at first glance.

**Comment by azoitl** [comment]
Thx this helps to narrow it down. I think I know what the problem is.

However you mention that there are also issue with the Palette. Can you tell more about it?

**Comment by rudoc** [comment]
> However you mention that there are also issue with the Palette. Can you tell more about it?

Before the fix, the `Palette` tab was improperly scaled / rendered too small:

<img width="1072" height="400" alt="Image" src="https://github.com/user-attachments/assets/7d79fdb5-2b1b-4f8a-8946-c597b378d5ed" />


After applying the fix, the `Palette` tab scales correctly.

<img width="810" height="469" alt="Image" src="https://github.com/user-attachments/assets/974acf16-aa3b-47db-8ce7-a47fa2c5418e" />

Since I use that functionality infrequently, I hadn't given it close attention.

**Comment by MandKastner** [comment]
I also noticed inserting a new FB does not place it correctly. I tried to insert the E_CTD block at the target position marked with the red X.

<img width="1709" height="658" alt="Image" src="https://github.com/user-attachments/assets/0ea54edf-62c2-4f76-b5ae-b3359df8ca74" />

**Comment by azoitl** [comment]
@MandKastner thx for pointing this out. This should be fixed with pr #1986.

Now I only have to fix the connection issue.

@rudoc thx for the information on the palette I fear for this I will need more time and a larger change. Maybe then something for 3.1.

**Comment by rudoc** [comment]
On the Windows version of the IDE, without the `-Ddraw2d.enableAutoscale=false` flag, function blocks are now displayed like this:

![Image](https://github.com/user-attachments/assets/751cc408-9076-44df-bf23-39f2815ac6ce)

The above option alone resolves the geometry problem for FBs:

![Image](https://github.com/user-attachments/assets/7057af43-393a-42b5-8001-a37fc798aed5)

```
4diac IDE 
Version: 3.1.0
Build id: 2026-02-17_1402
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 25.0.1+8-LTS
Java version: 25.0.1
```

**Comment by azoitl** [comment]
@rudoc I hope this will be fixed with the M3 release of Eclipse platform and Draw2d which is scheduled for this friday.

**Comment by franz-hoepfinger-4diac** [comment]
Hello, 

in 3.0.2 
4diac-ide_3.2.0-win32.win32.x86_64_nightly_2026-04-17_2003
this Problem is not fixed. 

pls note. 

Thanks

**Comment by azoitl** [comment]
@franz-hoepfinger-4diac can you be more specific what is not working? What would help is the specific use case, a screenshot, anything that helps us to recreate the problem. Please note that if you use groups, or expanded subapps that there we still have issues and there is an own issue tracking that.
